include:
  # Core Infrastructure
  - docker_servers/traefik/docker-compose.traefik.yml  # Main traefik configuration
  - docker_servers/postgres/docker-compose.postgres.yml # Database service
  - docker_servers/minio/docker-compose.minio.yml      # Object storage

networks:
  server-net:
    name: server-net
    driver: bridge
  traefik-net:
    name: traefik-net
    # external: true # Set to true if Traefik manages this network externally (e.g., `docker network create traefik-net`)
    # Otherwise, if it's just for this stack, set to false or remove 'external: true'.
    # For now, assuming it's managed within this stack for simplicity.
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
  minio_data:
  coolify_data:
  portainer_data:
  openwebui_data:
  ollama_data:
  openhands_data:
    # flowise_data: # Uncomment if flowise is changed to use a named volume
    # prometheus_data: # Add if prometheus service uses a named volume
    # testing_data: # Add if testing service uses a named volume
