version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_VECTOR}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432" # Only expose locally for security
    networks:
      - server-net
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

# Volumes and Networks are defined in the root docker-compose.yml
# volumes:
#   postgres_data: # This is now defined in the root docker-compose.yml

# networks:
#   server-net: # This is now defined in the root docker-compose.yml
#     external: false # Or true if defined elsewhere and you are connecting to it
