services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      # Configure data source (Prometheus)
      # - GF_INSTALL_PLUGINS=grafana-piechart-panel # Example of installing a plugin
    networks:
      - server-net
    labels:
      - "traefik.enable=true"
      # Routing rule based on the domain
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      # Apply basic authentication middleware
      - "traefik.http.routers.grafana.middlewares=basicauth@file"
      # Service definition pointing to the internal container port (3000 is default for Grafana)
      - "traefik.http.services.grafana.loadbalancer.server.port=${GRAFANA_HTTP_PORT:-3000}"

# Networks and Volumes are defined in the root docker-compose.yml
