# This file is intended to be a placeholder or for truly base services
# not defined elsewhere.
# Traefik is in docker_servers/base/docker-compose.traefik.yml
# Postgres is in docker_servers/postgres/docker-compose.postgres.yml
# Minio will be in docker_servers/minio/docker-compose.minio.yml (to be created)
# Coolify is in docker-compose.traefik.yml (to be moved)

# If there are other base services, they can be defined here.
# For now, this file can be left empty or with a comment.
# Example:
# services:
#   some-other-base-service:
#     image: some-image
#     # ... other configurations

# Networks and volumes are defined in the root docker-compose.yml
# or in the specific service files that use them if they are not shared.

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - server-net
    # No Traefik labels unless you need external DB access

networks:
  server-net:
    name: server-net
    driver: bridge

volumes:
  minio_data:
  postgres_data:
